### ISSUE TITLE
"Invalid" Schema created if type is unset

### ISSUE THREAD

**Issue by udoschneider** [zweidenker/JSONSchema#35]
If the schema does not provide a `type` property an invalid schema ` JSONSchemaAnyObject` might be produced. I.e. the following code does not raise an exception as required:
```smalltalk
|schema|
schema := JSONSchema fromString: '{"exclusiveMaximum":10}'.
schema validate: 11.
```
Adding a `type` property leads to the right schema being produced (`JSONSchemaNumber`) incl. matching constraints:
```smalltalk
|schema|
schema := JSONSchema fromString: '{"type":"number","exclusiveMaximum":10}'.
schema validate: 11.
```
I'm not 100% sure if `type` is a required property and thus schemas not specifing it might be invalid. However from reading the spec (and the test cases) I strongly assume that a schema without a `type` property is indeed valid. If this is the case the complete framework might have to be reorganized because it's (`type`) existence seems to be a very basic low-level assumption the framwork relies on.

**Comment by udoschneider** [comment]
It seems to be even worse. `type` is not a required property. Any you can also not infer the type from a constraint as multiple constraints for disjoint types may be used. So the following seems to be perfectly valid:
```json
{
    "maxItems":3,
    "maxProperties":3,
    "maxLength":3
}
```
This will match any object/dictionary, array or string as long as it has less 4 elements ...

From a package perspective this means that you cannot rely on `type` being set to attach the correct `JSONSchemaConstraint` instances. One possibility might be to allow `JSONSchemaAnyObject` to accept any constraint in `#constraintKeywords`. However this would require the constraint to have a way to check whether a given object can be validated at all given it's type. E.g. `JSONSchemaLengthConstraint` might need to verify if a given object is a `String` before trying to `#validate:`. Maybe we need to add an additional check to `JSONSchemaConstraint` subclasses that's called before `#validate:`. Something like a  `#canValidate:` test method. For `JSONSchemaLengthConstraint` this might be as simple as:
```smalltalk
canValidate: anObject
      ^ anObject isString
```

**Comment by noha** [comment]
I can have a look but my gut feeling is it has to be a any object with constraints

**Comment by noha** [comment]
I looked into it. I'm pretty sure we can rely on type because it does not make sense without type. Hence the existance of any type. And I don't think we have to reverse check types. I think there are always ways to specify bogus specs. We should not try to solve all problems that might appear. Early fail should be good enough.

**Comment by noha** [comment]
But I'm willing to discuss that further. Fix for this particular is coming in

**Comment by udoschneider** [comment]
I don't think it fixes the problem completely. Given the schema 

```smalltalk
schema := JSONSchema fromString: '{
    "maxItems":3,
    "maxProperties":3,
    "maxLength":3
}'.
```
and the following validation
```
schema validate: #( 1 2 3 4)
```

raises an error. The actual error is an error in the message generation in `JSONSchemaLengthConstraint>>#validate:` ... but the root cause is that an constraint only meant for strings is checked against an Array.

So either we'll check the supported type in `#validate:` in `JSONSchemaConstraint` subclasses (i.e. `#isKindOf:` or `#isXXXXX` tests) or we'll extract those type checks into seperate e.g. `#validateType:` methods called from `JSONSchema>>#validate:`. E.g.:

```smalltalk
JSONSchema>>#validate: anObject
	self validateType: anObject.
	self constraints
		do: [ :constraint | 
			constraint validateType
				ifTrue: [ constraint validate: anObject ] ]

JSONSchemaLengthConstraint>>#validateType: anObject
	^ anObject isKindOf: String	"or simply use #isString ?"
```
